In [48]:
import numpy as np
import pandas as pd

In [49]:
data = pd.read_csv("Iris.csv")
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [50]:
data['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [51]:
data['Species'] = data['Species'].replace({"Iris-setosa":1,"Iris-versicolor":2,"Iris-virginica":3})
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        1
1   2            4.9           3.0            1.4           0.2        1
2   3            4.7           3.2            1.3           0.2        1
3   4            4.6           3.1            1.5           0.2        1
4   5            5.0           3.6            1.4           0.2        1

In [52]:
x= data.iloc[:,1:6].values
x

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [4.9, 3. , 1.4, 0.2, 1. ],
       [4.7, 3.2, 1.3, 0.2, 1. ],
       [4.6, 3.1, 1.5, 0.2, 1. ],
       [5. , 3.6, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [4.6, 3.4, 1.4, 0.3, 1. ],
       [5. , 3.4, 1.5, 0.2, 1. ],
       [4.4, 2.9, 1.4, 0.2, 1. ],
       [4.9, 3.1, 1.5, 0.1, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [4.8, 3.4, 1.6, 0.2, 1. ],
       [4.8, 3. , 1.4, 0.1, 1. ],
       [4.3, 3. , 1.1, 0.1, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [4.6, 3.6, 1. , 0.2, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [4.8, 3.4, 1.9, 0.2, 1. ],
       [5. , 3. , 1.6, 0.2, 1. ],
       [5. , 3.4, 1.6, 0.4, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [4.7, 3

In [53]:
y = data.iloc[:,5].values
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3], dtype=int64)

In [54]:
from sklearn.model_selection import  train_test_split

In [55]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix,accuracy_score,cohen_kappa_score,classification_report

In [56]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3,random_state=0)
glt = GaussianNB()
glt.fit(xtrain,ytrain)
prdict = glt.predict(xtest)
print("Confusion matrix :: ",confusion_matrix(ytest,prdict))
print("Accuracy :: ",accuracy_score(ytest,prdict))
print("Kappa :: ",cohen_kappa_score(ytest,prdict))
print("Classification :: ",classification_report(ytest,prdict))

Confusion matrix ::  [[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
Accuracy ::  1.0
Kappa ::  1.0
Classification ::                precision    recall  f1-score   support

           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00        18
           3       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [57]:
from sklearn.neighbors import KNeighborsClassifier
# help(KNeighborsClassifier)
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(xtrain,ytrain)
prdict=knn.predict(xtest)
print("Confusion matrix :: ",confusion_matrix(ytest,prdict))
print("Accuracy :: ",accuracy_score(ytest,prdict))
print("Kappa :: ",cohen_kappa_score(ytest,prdict))
print("Classification :: ",classification_report(ytest,prdict))

Confusion matrix ::  [[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
Accuracy ::  1.0
Kappa ::  1.0
Classification ::                precision    recall  f1-score   support

           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00        18
           3       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [58]:
from sklearn .ensemble import RandomForestClassifier
# help(RandomForestClassifier)
rm = RandomForestClassifier(n_estimators=20)
rm.fit(xtrain,ytrain)
prdict= rm.predict(xtest)
print("Confusion matrix :: ",confusion_matrix(ytest,prdict))
print("Accuracy :: ",accuracy_score(ytest,prdict))
print("Kappa :: ",cohen_kappa_score(ytest,prdict))
print("Classification :: ",classification_report(ytest,prdict))


Confusion matrix ::  [[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
Accuracy ::  1.0
Kappa ::  1.0
Classification ::                precision    recall  f1-score   support

           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00        18
           3       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [59]:
from  sklearn import tree
dd = tree.DecisionTreeClassifier()
dd.fit(xtrain,ytrain)
prdict= dd.predict(xtest)
print("Confusion matrix :: ",confusion_matrix(ytest,prdict))
print("Accuracy :: ",accuracy_score(ytest,prdict))
print("Kappa :: ",cohen_kappa_score(ytest,prdict))
print("Classification :: ",classification_report(ytest,prdict))


Confusion matrix ::  [[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
Accuracy ::  1.0
Kappa ::  1.0
Classification ::                precision    recall  f1-score   support

           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00        18
           3       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [60]:
from sklearn.svm import SVC
se = SVC()
se.fit(xtrain,ytrain)
prdict = se.predict(xtest)
print("Confusion matrix :: ",confusion_matrix(ytest,prdict))
print("Accuracy :: ",accuracy_score(ytest,prdict))
print("Kappa :: ",cohen_kappa_score(ytest,prdict))
print("Classification :: ",classification_report(ytest,prdict))



Confusion matrix ::  [[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
Accuracy ::  1.0
Kappa ::  1.0
Classification ::                precision    recall  f1-score   support

           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00        18
           3       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

